---
# Role tasks for RHEL/Centos 6

- block:
    - name: Adjust /etc/inittab to require root password in single mode
      lineinfile:
        path: /etc/inittab
        line: 'su:S:wait:/sbin/sulogin'
        insertbefore: "^id:3:initdefault:"
        state: present

    - name: Adjust /etc/sysconfig/init to require root password in single mode
      lineinfile:
        path: /etc/sysconfig/init
        regexp: '^SINGLE='
        line: 'SINGLE=/sbin/sulogin'
  tags:
    - role::single_mode
