---

- name: Setup config to require root password in single mode
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/rescue.service
    regexp: '^ExecStart'
    line: >-
      ExecStart=-/bin/sh -c
      "/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"
  tags:
    - role::single_mode
