---

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      rhel: 6
      fedora: 29

# Role tasks

- block:
    - include_tasks: el_6.yml
      when:
        - ansible_facts.distribution | lower in ["centos", "rehat"]
        - ansible_facts.distribution_major_version is version('6', '==')

    - include_tasks: el_7.yml
      when:
        - ansible_facts.distribution | lower in ["centos", "rehat"]
        - ansible_facts.distribution_major_version is version('7', '==')

    - include_tasks: fedora.yml
      when: ansible_facts.distribution | lower in ["fedora"]
  tags:
    - role::single_mode
