---
# Role tasks
- block:
    - name: Adjust /etc/inittab to require root password in single mode
      lineinfile:
        path: /etc/inittab
        line: 'su:S:wait:/sbin/sulogin'
        insertbefore: "^id:3:initdefault:"
        state: present

    - name: Adjust /etc/sysconfig/init to require root password in single mode
      lineinfile:
        path: /etc/sysconfig/init
        regexp: '^SINGLE='
        line: 'SINGLE=/sbin/sulogin'
  when:
    - ansible_facts.distribution | lower in ["rhel", "centos"]
    - ansible_facts.distribution_major_version == '6'

- block:
    - name: Ensure config require root password in single mode in centos 7
      lineinfile:
        path: /usr/lib/systemd/system/rescue.service
        regexp: '^ExecStart'
        line: 'ExecStart=-/bin/sh -c "/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
  when:
    - ansible_facts.distribution | lower in ["rhel", "centos"]
    - ansible_facts.distribution_major_version == '7'

- block:
    - name: Ensure config require root password in single mode in fedora
      lineinfile:
        path: /usr/lib/systemd/system/rescue.service
        regexp: '^ExecStart'
        line: 'ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue'
  when:
    - ansible_facts.distribution | lower in ["fedora"]
