---

- name: Setup single mode
  block:
    - ansible.builtin.include_tasks: el_6.yml
      when: ansible_facts.distribution_major_version is version('6', '==')

    - ansible.builtin.include_tasks: el_7.yml
      when: ansible_facts.distribution_major_version is version('7', '==')

    - ansible.builtin.include_tasks: systemd.yml
      when: ansible_facts.distribution_major_version is version('7', '>')
  tags:
    - role::single_mode
