---

- name: Setup config to require root password in single mode
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/rescue.service
    regexp: '^ExecStart'
    line: 'ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue'
  tags:
    - role::single_mode
