---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check sushell is configured in RHEL and CentOS 6
      shell: grep --fixed-strings sulogin "{{ item }}"
      changed_when: no
      loop:
        - /etc/inittab
        - /etc/sysconfig/init
      when:
        - ansible_facts.distribution | lower in ["centos", "redhat"]
        - ansible_facts.distribution_major_version is version('6', '==')

    - name: Check sushell is configured in RHEL and CentOS 7
      shell: grep --fixed-strings sulogin "{{ item }}"
      changed_when: no
      loop:
        - /usr/lib/systemd/system/rescue.service
      when:
        - ansible_facts.distribution | lower in ["rhel", "centos", "fedora"]
        - ansible_facts.distribution_major_version is version('7', '>=')
